from __future__ import annotations

import sqlalchemy as sa


def test_upgrade_downgrade_roundtrip(alembic_config, test_db_url):
    from alembic import command

    command.upgrade(alembic_config, "head")
    command.downgrade(alembic_config, "base")
    command.upgrade(alembic_config, "head")

    eng = sa.create_engine(test_db_url)
    with eng.connect() as c:
        tables = set(
            c.execute(
                sa.text("select tablename from pg_tables where schemaname = 'public'")
            ).scalars()
        )
    eng.dispose()
    assert {"overture_places", "dohmh_establishments", "boba_shops", "ingest_runs"} <= tables


def test_models_match_migrations(alembic_config):
    """alembic check == no pending autogenerate diff (the schema contract)."""
    from alembic import command
    from alembic.util.exc import AutogenerateDiffsDetected

    command.upgrade(alembic_config, "head")
    try:
        command.check(alembic_config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
        raise AssertionError(f"models drifted from migrations: {exc}") from exc
