"""schema

Revision ID: 005dda34b371
Revises:
Create Date: 2026-09-01 20:14:47.646515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "005dda34b371"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "boroughs",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_boroughs")),
    )
    op.create_geospatial_index(
        "idx_boroughs_geom",
        "boroughs",
        ["geom"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_table(
        "dohmh_establishments",
        sa.Column("camis", sa.String(), nullable=False),
        sa.Column("dba", sa.String(), nullable=True),
        sa.Column("boro", sa.String(), nullable=True),
        sa.Column("building", sa.String(), nullable=True),
        sa.Column("street", sa.String(), nullable=True),
        sa.Column("zipcode", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("cuisine_description", sa.String(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("first_inspection_date", sa.Date(), nullable=True),
        sa.Column("last_inspection_date", sa.Date(), nullable=True),
        sa.Column("last_record_date", sa.Date(), nullable=True),
        sa.Column("closed_flag", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("closed_date", sa.Date(), nullable=True),
        sa.Column("reopened_date", sa.Date(), nullable=True),
        sa.Column("boba_name_match", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "closed_flag is false or closed_date is not null",
            name=op.f("ck_dohmh_establishments_closed_date"),
        ),
        sa.PrimaryKeyConstraint("camis", name=op.f("pk_dohmh_establishments")),
    )
    op.create_geospatial_index(
        "idx_dohmh_establishments_geom",
        "dohmh_establishments",
        ["geom"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        op.f("ix_dohmh_establishments_boba_name_match"),
        "dohmh_establishments",
        ["boba_name_match"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dohmh_establishments_closed_flag"),
        "dohmh_establishments",
        ["closed_flag"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dohmh_establishments_cuisine_description"),
        "dohmh_establishments",
        ["cuisine_description"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dohmh_establishments_dba"), "dohmh_establishments", ["dba"], unique=False
    )
    op.create_table(
        "ingest_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="running", nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_version", sa.String(), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("kept_count", sa.Integer(), nullable=True),
        sa.Column("min_date", sa.Date(), nullable=True),
        sa.Column("max_date", sa.Date(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.CheckConstraint(
            "status in ('running', 'ok', 'failed')", name=op.f("ck_ingest_runs_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_runs")),
    )
    op.create_index(op.f("ix_ingest_runs_source"), "ingest_runs", ["source"], unique=False)
    op.create_geospatial_table(
        "overture_places",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("category_primary", sa.String(), nullable=True),
        sa.Column("categories", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("brand", sa.String(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("operating_status", sa.String(), nullable=True),
        sa.Column("addr_freeform", sa.String(), nullable=True),
        sa.Column("locality", sa.String(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("postcode", sa.String(), nullable=True),
        sa.Column("website", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("source_update_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("overture_release", sa.String(), nullable=True),
        sa.Column("first_seen_release", sa.String(), nullable=True),
        sa.Column("last_seen_release", sa.String(), nullable=True),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence is null or (confidence >= 0 and confidence <= 1)",
            name=op.f("ck_overture_places_confidence"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_overture_places")),
    )
    op.create_geospatial_index(
        "idx_overture_places_geom",
        "overture_places",
        ["geom"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        op.f("ix_overture_places_category_primary"),
        "overture_places",
        ["category_primary"],
        unique=False,
    )
    op.create_index(
        op.f("ix_overture_places_operating_status"),
        "overture_places",
        ["operating_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_overture_places_overture_release"),
        "overture_places",
        ["overture_release"],
        unique=False,
    )
    op.create_geospatial_table(
        "boba_shops",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("overture_id", sa.String(), nullable=True),
        sa.Column("camis", sa.String(), nullable=True),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("borough", sa.String(), nullable=True),
        sa.Column("first_seen_date", sa.Date(), nullable=True),
        sa.Column("first_seen_source", sa.String(), nullable=True),
        sa.Column("last_seen_date", sa.Date(), nullable=True),
        sa.Column("closed_date", sa.Date(), nullable=True),
        sa.Column("closed_source", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("status_basis", sa.String(), nullable=True),
        sa.Column("identified_by", sa.String(), nullable=True),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "first_seen_source is null or first_seen_source in ('dohmh_prepermit_inspection', 'dohmh_first_inspection', 'overture_release')",
            name=op.f("ck_boba_shops_first_seen_source"),
        ),
        sa.CheckConstraint(
            "identified_by in ('overture_category', 'name_pattern', 'both', 'propagated')",
            name=op.f("ck_boba_shops_identified_by"),
        ),
        sa.CheckConstraint(
            "status in ('open', 'closed', 'unknown')", name=op.f("ck_boba_shops_status")
        ),
        sa.CheckConstraint(
            "status_basis in ('dohmh_active', 'yelp_open', 'overture_open', 'yelp_closed', 'dohmh_closed_by_dohmh', 'dohmh_inactive', 'overture_permanently_closed', 'none')",
            name=op.f("ck_boba_shops_status_basis"),
        ),
        sa.CheckConstraint(
            "first_seen_date is null or last_seen_date is null or last_seen_date >= first_seen_date",
            name=op.f("ck_boba_shops_date_order"),
        ),
        sa.ForeignKeyConstraint(
            ["camis"],
            ["dohmh_establishments.camis"],
            name=op.f("fk_boba_shops_camis_dohmh_establishments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["overture_id"],
            ["overture_places.id"],
            name=op.f("fk_boba_shops_overture_id_overture_places"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_boba_shops")),
    )
    op.create_geospatial_index(
        "idx_boba_shops_geom",
        "boba_shops",
        ["geom"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(op.f("ix_boba_shops_borough"), "boba_shops", ["borough"], unique=False)
    op.create_index(op.f("ix_boba_shops_camis"), "boba_shops", ["camis"], unique=False)
    op.create_index(
        op.f("ix_boba_shops_first_seen_date"), "boba_shops", ["first_seen_date"], unique=False
    )
    op.create_index(
        op.f("ix_boba_shops_identified_by"), "boba_shops", ["identified_by"], unique=False
    )
    op.create_index(op.f("ix_boba_shops_overture_id"), "boba_shops", ["overture_id"], unique=False)
    op.create_index(op.f("ix_boba_shops_status"), "boba_shops", ["status"], unique=False)
    op.create_index(
        op.f("ix_boba_shops_status_basis"), "boba_shops", ["status_basis"], unique=False
    )
    op.create_table(
        "dohmh_inspections",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("camis", sa.String(), nullable=False),
        sa.Column("inspection_date", sa.Date(), nullable=True),
        sa.Column("inspection_type", sa.String(), nullable=True),
        sa.Column("action", sa.String(), nullable=True),
        sa.Column("critical_flag", sa.String(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("grade", sa.String(), nullable=True),
        sa.Column("grade_date", sa.Date(), nullable=True),
        sa.Column("record_date", sa.Date(), nullable=True),
        sa.Column("violation_code", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["camis"],
            ["dohmh_establishments.camis"],
            name=op.f("fk_dohmh_inspections_camis_dohmh_establishments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dohmh_inspections")),
        sa.UniqueConstraint(
            "camis",
            "inspection_date",
            "violation_code",
            "action",
            name="uq_dohmh_inspection_row",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        op.f("ix_dohmh_inspections_camis"), "dohmh_inspections", ["camis"], unique=False
    )
    op.create_index(
        op.f("ix_dohmh_inspections_inspection_date"),
        "dohmh_inspections",
        ["inspection_date"],
        unique=False,
    )
    op.create_table(
        "place_matches",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("overture_id", sa.String(), nullable=False),
        sa.Column("camis", sa.String(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("method", sa.String(), nullable=True),
        sa.Column("distance_m", sa.Float(), nullable=True),
        sa.Column("name_similarity", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "score is null or (score >= 0 and score <= 100)", name=op.f("ck_place_matches_score")
        ),
        sa.ForeignKeyConstraint(
            ["camis"],
            ["dohmh_establishments.camis"],
            name=op.f("fk_place_matches_camis_dohmh_establishments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["overture_id"],
            ["overture_places.id"],
            name=op.f("fk_place_matches_overture_id_overture_places"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_place_matches")),
        sa.UniqueConstraint("overture_id", "camis", name="uq_place_match"),
    )
    op.create_index(op.f("ix_place_matches_camis"), "place_matches", ["camis"], unique=False)
    op.create_index(
        op.f("ix_place_matches_overture_id"), "place_matches", ["overture_id"], unique=False
    )
    op.create_table(
        "yelp_status",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("overture_id", sa.String(), nullable=True),
        sa.Column("camis", sa.String(), nullable=True),
        sa.Column("yelp_id", sa.String(), nullable=True),
        sa.Column("yelp_name", sa.String(), nullable=True),
        sa.Column("is_closed", sa.Boolean(), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("review_count", sa.Integer(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("match_score", sa.Float(), nullable=True),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["camis"],
            ["dohmh_establishments.camis"],
            name=op.f("fk_yelp_status_camis_dohmh_establishments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["overture_id"],
            ["overture_places.id"],
            name=op.f("fk_yelp_status_overture_id_overture_places"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_yelp_status")),
        sa.UniqueConstraint(
            "overture_id", "camis", name="uq_yelp_status_key", postgresql_nulls_not_distinct=True
        ),
    )
    op.create_index(op.f("ix_yelp_status_camis"), "yelp_status", ["camis"], unique=False)
    op.create_index(
        op.f("ix_yelp_status_overture_id"), "yelp_status", ["overture_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_yelp_status_overture_id"), table_name="yelp_status")
    op.drop_index(op.f("ix_yelp_status_camis"), table_name="yelp_status")
    op.drop_table("yelp_status")
    op.drop_index(op.f("ix_place_matches_overture_id"), table_name="place_matches")
    op.drop_index(op.f("ix_place_matches_camis"), table_name="place_matches")
    op.drop_table("place_matches")
    op.drop_index(op.f("ix_dohmh_inspections_inspection_date"), table_name="dohmh_inspections")
    op.drop_index(op.f("ix_dohmh_inspections_camis"), table_name="dohmh_inspections")
    op.drop_table("dohmh_inspections")
    op.drop_index(op.f("ix_boba_shops_status_basis"), table_name="boba_shops")
    op.drop_index(op.f("ix_boba_shops_status"), table_name="boba_shops")
    op.drop_index(op.f("ix_boba_shops_overture_id"), table_name="boba_shops")
    op.drop_index(op.f("ix_boba_shops_identified_by"), table_name="boba_shops")
    op.drop_index(op.f("ix_boba_shops_first_seen_date"), table_name="boba_shops")
    op.drop_index(op.f("ix_boba_shops_camis"), table_name="boba_shops")
    op.drop_index(op.f("ix_boba_shops_borough"), table_name="boba_shops")
    op.drop_geospatial_index(
        "idx_boba_shops_geom", table_name="boba_shops", postgresql_using="gist", column_name="geom"
    )
    op.drop_geospatial_table("boba_shops")
    op.drop_index(op.f("ix_overture_places_overture_release"), table_name="overture_places")
    op.drop_index(op.f("ix_overture_places_operating_status"), table_name="overture_places")
    op.drop_index(op.f("ix_overture_places_category_primary"), table_name="overture_places")
    op.drop_geospatial_index(
        "idx_overture_places_geom",
        table_name="overture_places",
        postgresql_using="gist",
        column_name="geom",
    )
    op.drop_geospatial_table("overture_places")
    op.drop_index(op.f("ix_ingest_runs_source"), table_name="ingest_runs")
    op.drop_table("ingest_runs")
    op.drop_index(op.f("ix_dohmh_establishments_dba"), table_name="dohmh_establishments")
    op.drop_index(
        op.f("ix_dohmh_establishments_cuisine_description"), table_name="dohmh_establishments"
    )
    op.drop_index(op.f("ix_dohmh_establishments_closed_flag"), table_name="dohmh_establishments")
    op.drop_index(
        op.f("ix_dohmh_establishments_boba_name_match"), table_name="dohmh_establishments"
    )
    op.drop_geospatial_index(
        "idx_dohmh_establishments_geom",
        table_name="dohmh_establishments",
        postgresql_using="gist",
        column_name="geom",
    )
    op.drop_geospatial_table("dohmh_establishments")
    op.drop_geospatial_index(
        "idx_boroughs_geom", table_name="boroughs", postgresql_using="gist", column_name="geom"
    )
    op.drop_geospatial_table("boroughs")
    # ### end Alembic commands ###
