"""boroughs table

Revision ID: 46eef0a981d0
Revises: 96006d515b92
Create Date: 2026-09-01 18:52:52.783487

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "46eef0a981d0"
down_revision: Union[str, Sequence[str], None] = "96006d515b92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "boroughs",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_boroughs")),
    )
    op.create_geospatial_index(
        "idx_boroughs_geom",
        "boroughs",
        ["geom"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "idx_boroughs_geom", table_name="boroughs", postgresql_using="gist", column_name="geom"
    )
    op.drop_geospatial_table("boroughs")
    # ### end Alembic commands ###
