"""schema

Revision ID: 84673e8d52ca
Revises:
Create Date: 2026-09-01 21:31:47.912971

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "84673e8d52ca"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "boroughs",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_boroughs")),
    )
    op.create_geospatial_index(
        "idx_boroughs_geom",
        "boroughs",
        ["geom"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_table(
        "dohmh_establishments",
        sa.Column("camis", sa.String(), nullable=False),
        sa.Column("dba", sa.String(), nullable=True),
        sa.Column("boro", sa.String(), nullable=True),
        sa.Column("building", sa.String(), nullable=True),
        sa.Column("street", sa.String(), nullable=True),
        sa.Column("zipcode", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("cuisine_description", sa.String(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("first_inspection_date", sa.Date(), nullable=True),
        sa.Column("last_inspection_date", sa.Date(), nullable=True),
        sa.Column("last_record_date", sa.Date(), nullable=True),
        sa.Column("closed_flag", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("closed_date", sa.Date(), nullable=True),
        sa.Column("reopened_date", sa.Date(), nullable=True),
        sa.Column("boba_name_match", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "closed_flag is false or closed_date is not null",
            name=op.f("ck_dohmh_establishments_closed_date"),
        ),
        sa.PrimaryKeyConstraint("camis", name=op.f("pk_dohmh_establishments")),
    )
    op.create_geospatial_index(
        "idx_dohmh_establishments_geom",
        "dohmh_establishments",
        ["geom"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        op.f("ix_dohmh_establishments_boba_name_match"),
        "dohmh_establishments",
        ["boba_name_match"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dohmh_establishments_closed_flag"),
        "dohmh_establishments",
        ["closed_flag"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dohmh_establishments_cuisine_description"),
        "dohmh_establishments",
        ["cuisine_description"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dohmh_establishments_dba"), "dohmh_establishments", ["dba"], unique=False
    )
    op.create_table(
        "ingest_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="running", nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_version", sa.String(), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("kept_count", sa.Integer(), nullable=True),
        sa.Column("min_date", sa.Date(), nullable=True),
        sa.Column("max_date", sa.Date(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.CheckConstraint(
            "status in ('running', 'ok', 'failed')", name=op.f("ck_ingest_runs_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_runs")),
    )
    op.create_index(op.f("ix_ingest_runs_source"), "ingest_runs", ["source"], unique=False)
    op.create_geospatial_table(
        "yelp_businesses",
        sa.Column("yelp_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("is_closed", sa.Boolean(), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("review_count", sa.Integer(), nullable=True),
        sa.Column("price", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("categories", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("zip", sa.String(), nullable=True),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("yelp_id", name=op.f("pk_yelp_businesses")),
    )
    op.create_geospatial_index(
        "idx_yelp_businesses_geom",
        "yelp_businesses",
        ["geom"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(op.f("ix_yelp_businesses_name"), "yelp_businesses", ["name"], unique=False)
    op.create_geospatial_table(
        "boba_shops",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("camis", sa.String(), nullable=True),
        sa.Column("yelp_id", sa.String(), nullable=True),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("borough", sa.String(), nullable=True),
        sa.Column("first_seen_date", sa.Date(), nullable=True),
        sa.Column("first_seen_source", sa.String(), nullable=True),
        sa.Column("last_seen_date", sa.Date(), nullable=True),
        sa.Column("closed_date", sa.Date(), nullable=True),
        sa.Column("closed_source", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("status_basis", sa.String(), nullable=True),
        sa.Column("identified_by", sa.String(), nullable=True),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "first_seen_source is null or first_seen_source = 'dohmh_first_inspection'",
            name=op.f("ck_boba_shops_first_seen_source"),
        ),
        sa.CheckConstraint(
            "identified_by in ('yelp_category', 'name_pattern')",
            name=op.f("ck_boba_shops_identified_by"),
        ),
        sa.CheckConstraint(
            "status in ('open', 'closed', 'unknown')", name=op.f("ck_boba_shops_status")
        ),
        sa.CheckConstraint(
            "status_basis in ('dohmh_active', 'yelp_open', 'yelp_closed', 'dohmh_closed_by_dohmh', 'dohmh_inactive', 'none')",
            name=op.f("ck_boba_shops_status_basis"),
        ),
        sa.CheckConstraint(
            "first_seen_date is null or last_seen_date is null or last_seen_date >= first_seen_date",
            name=op.f("ck_boba_shops_date_order"),
        ),
        sa.ForeignKeyConstraint(
            ["camis"],
            ["dohmh_establishments.camis"],
            name=op.f("fk_boba_shops_camis_dohmh_establishments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["yelp_id"],
            ["yelp_businesses.yelp_id"],
            name=op.f("fk_boba_shops_yelp_id_yelp_businesses"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_boba_shops")),
    )
    op.create_geospatial_index(
        "idx_boba_shops_geom",
        "boba_shops",
        ["geom"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(op.f("ix_boba_shops_borough"), "boba_shops", ["borough"], unique=False)
    op.create_index(op.f("ix_boba_shops_camis"), "boba_shops", ["camis"], unique=False)
    op.create_index(
        op.f("ix_boba_shops_first_seen_date"), "boba_shops", ["first_seen_date"], unique=False
    )
    op.create_index(
        op.f("ix_boba_shops_identified_by"), "boba_shops", ["identified_by"], unique=False
    )
    op.create_index(op.f("ix_boba_shops_status"), "boba_shops", ["status"], unique=False)
    op.create_index(
        op.f("ix_boba_shops_status_basis"), "boba_shops", ["status_basis"], unique=False
    )
    op.create_index(op.f("ix_boba_shops_yelp_id"), "boba_shops", ["yelp_id"], unique=False)
    op.create_table(
        "dohmh_inspections",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("camis", sa.String(), nullable=False),
        sa.Column("inspection_date", sa.Date(), nullable=True),
        sa.Column("inspection_type", sa.String(), nullable=True),
        sa.Column("action", sa.String(), nullable=True),
        sa.Column("critical_flag", sa.String(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("grade", sa.String(), nullable=True),
        sa.Column("grade_date", sa.Date(), nullable=True),
        sa.Column("record_date", sa.Date(), nullable=True),
        sa.Column("violation_code", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["camis"],
            ["dohmh_establishments.camis"],
            name=op.f("fk_dohmh_inspections_camis_dohmh_establishments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dohmh_inspections")),
        sa.UniqueConstraint(
            "camis",
            "inspection_date",
            "violation_code",
            "action",
            name="uq_dohmh_inspection_row",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        op.f("ix_dohmh_inspections_camis"), "dohmh_inspections", ["camis"], unique=False
    )
    op.create_index(
        op.f("ix_dohmh_inspections_inspection_date"),
        "dohmh_inspections",
        ["inspection_date"],
        unique=False,
    )
    op.create_table(
        "yelp_matches",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("yelp_id", sa.String(), nullable=False),
        sa.Column("camis", sa.String(), nullable=True),
        sa.Column("camis_score", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["camis"],
            ["dohmh_establishments.camis"],
            name=op.f("fk_yelp_matches_camis_dohmh_establishments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["yelp_id"],
            ["yelp_businesses.yelp_id"],
            name=op.f("fk_yelp_matches_yelp_id_yelp_businesses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_yelp_matches")),
        sa.UniqueConstraint("yelp_id", name="uq_yelp_matches_yelp_id"),
    )
    op.create_index(op.f("ix_yelp_matches_camis"), "yelp_matches", ["camis"], unique=False)
    op.create_index(op.f("ix_yelp_matches_yelp_id"), "yelp_matches", ["yelp_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_yelp_matches_yelp_id"), table_name="yelp_matches")
    op.drop_index(op.f("ix_yelp_matches_camis"), table_name="yelp_matches")
    op.drop_table("yelp_matches")
    op.drop_index(op.f("ix_dohmh_inspections_inspection_date"), table_name="dohmh_inspections")
    op.drop_index(op.f("ix_dohmh_inspections_camis"), table_name="dohmh_inspections")
    op.drop_table("dohmh_inspections")
    op.drop_index(op.f("ix_boba_shops_yelp_id"), table_name="boba_shops")
    op.drop_index(op.f("ix_boba_shops_status_basis"), table_name="boba_shops")
    op.drop_index(op.f("ix_boba_shops_status"), table_name="boba_shops")
    op.drop_index(op.f("ix_boba_shops_identified_by"), table_name="boba_shops")
    op.drop_index(op.f("ix_boba_shops_first_seen_date"), table_name="boba_shops")
    op.drop_index(op.f("ix_boba_shops_camis"), table_name="boba_shops")
    op.drop_index(op.f("ix_boba_shops_borough"), table_name="boba_shops")
    op.drop_geospatial_index(
        "idx_boba_shops_geom", table_name="boba_shops", postgresql_using="gist", column_name="geom"
    )
    op.drop_geospatial_table("boba_shops")
    op.drop_index(op.f("ix_yelp_businesses_name"), table_name="yelp_businesses")
    op.drop_geospatial_index(
        "idx_yelp_businesses_geom",
        table_name="yelp_businesses",
        postgresql_using="gist",
        column_name="geom",
    )
    op.drop_geospatial_table("yelp_businesses")
    op.drop_index(op.f("ix_ingest_runs_source"), table_name="ingest_runs")
    op.drop_table("ingest_runs")
    op.drop_index(op.f("ix_dohmh_establishments_dba"), table_name="dohmh_establishments")
    op.drop_index(
        op.f("ix_dohmh_establishments_cuisine_description"), table_name="dohmh_establishments"
    )
    op.drop_index(op.f("ix_dohmh_establishments_closed_flag"), table_name="dohmh_establishments")
    op.drop_index(
        op.f("ix_dohmh_establishments_boba_name_match"), table_name="dohmh_establishments"
    )
    op.drop_geospatial_index(
        "idx_dohmh_establishments_geom",
        table_name="dohmh_establishments",
        postgresql_using="gist",
        column_name="geom",
    )
    op.drop_geospatial_table("dohmh_establishments")
    op.drop_geospatial_index(
        "idx_boroughs_geom", table_name="boroughs", postgresql_using="gist", column_name="geom"
    )
    op.drop_geospatial_table("boroughs")
    # ### end Alembic commands ###
