"""boba_shops.identified_by

Revision ID: 96006d515b92
Revises: cac6c6465281
Create Date: 2026-09-01 18:09:47.200865

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "96006d515b92"
down_revision: Union[str, Sequence[str], None] = "cac6c6465281"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("boba_shops", sa.Column("identified_by", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_boba_shops_identified_by"), "boba_shops", ["identified_by"], unique=False
    )
    op.create_check_constraint(
        op.f("ck_boba_shops_identified_by"),
        "boba_shops",
        "identified_by in ('overture_category', 'name_pattern', 'both', 'propagated')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_boba_shops_identified_by"), "boba_shops", type_="check")
    op.drop_index(op.f("ix_boba_shops_identified_by"), table_name="boba_shops")
    op.drop_column("boba_shops", "identified_by")
    # ### end Alembic commands ###
