"""boba_shops.status_basis

Revision ID: ccb337ef0b71
Revises: 46eef0a981d0
Create Date: 2026-09-01 19:28:26.658841

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ccb337ef0b71"
down_revision: Union[str, Sequence[str], None] = "46eef0a981d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("boba_shops", sa.Column("status_basis", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_boba_shops_status_basis"), "boba_shops", ["status_basis"], unique=False
    )
    op.create_check_constraint(
        op.f("ck_boba_shops_status_basis"),
        "boba_shops",
        "status_basis in ('dohmh_active', 'overture_open', 'dohmh_closed_by_dohmh', 'dohmh_inactive', 'overture_permanently_closed', 'none')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_boba_shops_status_basis"), "boba_shops", type_="check")
    op.drop_index(op.f("ix_boba_shops_status_basis"), table_name="boba_shops")
    op.drop_column("boba_shops", "status_basis")
    # ### end Alembic commands ###
